name: pet_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  get:
  intl: ^0.20.2
  flutter_screenutil:
  fluttertoast: ^8.2.12
  flutter_svg: ^2.0.10+1
  shimmer: ^3.0.0
  cached_network_image: ^3.3.1
  #device_preview: ^1.2.0
  google_fonts: ^6.2.1
  pin_code_fields: ^8.0.1
  image_picker: ^1.1.2
  http_parser: ^4.0.2
  http: ^1.2.2
  mime: ^1.0.5
  flutter_spinkit: ^5.2.1
  html: ^0.15.5
  shared_preferences: ^2.3.3
  socket_io_client: ^3.0.1
  carousel_slider: ^5.0.0
  dotted_border: ^2.1.0
  table_calendar: ^3.1.3
  flutter_asset_generator: ^1.2.0
  country_code_picker: ^3.2.0
  font_awesome_flutter: ^10.8.0
  share_plus: ^10.1.4
  flutter_inset_shadow:
  pinput: ^5.0.0
  gap: ^3.0.1
  go_router: ^14.3.0
  readmore: ^3.0.0
  fpdart: ^1.1.0
  logger: ^2.4.0
  internet_connection_checker_plus: ^2.5.2
  get_it: ^8.0.1
  infinite_scroll_pagination: ^4.0.0
  timeago: ^3.7.0
  iconsax: ^0.0.8
  jwt_decoder: ^2.0.1
  flutter_animate: ^4.5.2
  flutter_widget_from_html: ^0.16.0
  dropdown_button2: ^2.3.9
  lottie: ^3.3.1
  flutter_switch: ^0.3.2
  flutter_easy_faq: ^1.0.1
  fl_chart: ^1.0.0
  url_launcher: ^6.3.2
  google_maps_flutter: ^2.12.3
  flutter_rating_bar: ^4.0.1
  geolocator: ^14.0.2
  map_location_picker: ^2.0.3
  purchases_flutter:
  file_picker: ^9.0.2
  permission_handler: ^11.3.1
  open_file: ^3.0.5
  flutter_inappwebview: ^6.1.5
  badges: ^3.1.2
  timeago_flutter: ^3.7.0
  shadify: ^1.0.0

dev_dependencies:
  build_runner: ^2.4.10
  flutter_gen_runner: null
  json_serializable: ^6.2.0
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.4

flutter_gen:
  output: lib/core/custom_assets/
  line_length: 80
  integrations:
    flutter_svg: true

flutter_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/app_icon/icon.png"

flutter:
  uses-material-design: true

  assets:
    - assets/fonts/
    - assets/icons/
    - assets/images/
    - assets/animation/
    - assets/app_icon/icon.png

  fonts:
    - family: Bold
      fonts:
        - asset: assets/fonts/Poppins-Bold.ttf
    - family: Light
      fonts:
        - asset: assets/fonts/Poppins-Light.ttf
    - family: Medium
      fonts:
        - asset: assets/fonts/Poppins-Medium.ttf
